openapi: 3.0.1
info:
  description: 'film description'
  version: 1.0.0
  title: film API
paths:
  /api/film/{id}:
    get:
      operationId: obtenirFilm
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filmDto'

components:
  schemas:
    filmDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        titre:
          type: string
        description:
          type: string
        acteurs:
          type: array
          items:
            $ref: '#/components/schemas/acteurDto'
      xml:
        name: film
    acteurDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nom:
          type: string
        prenom:
          type: string